# Generated by Django 5.0 on 2023-12-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.CharField(max_length=50)),
                ('pembeli', models.CharField(max_length=50)),
                ('varian', models.CharField(max_length=50)),
                ('jumlah_pesanan', models.CharField(max_length=50)),
            ],
        ),
    ]
